"""add_macro_targets

Revision ID: 0098dca6dc9e
Revises: c0a8f9c1e149
Create Date: 2026-04-29 13:54:14.285343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0098dca6dc9e'
down_revision: Union[str, Sequence[str], None] = 'c0a8f9c1e149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_carbs_target', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('daily_fats_target', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_fats_target')
    op.drop_column('users', 'daily_carbs_target')
    # ### end Alembic commands ###
