"""embedding_versioning

Revision ID: 51fbb016fab4
Revises: 00a251dc563f
Create Date: 2026-05-06 12:32:12.465422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fbb016fab4'
down_revision: Union[str, Sequence[str], None] = '00a251dc563f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('embedding_dim', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('embedding_timestamp', sa.BigInteger(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'embedding_timestamp')
    op.drop_column('recipes', 'embedding_dim')
    op.drop_column('recipes', 'embedding_model')
    # ### end Alembic commands ###
