"""optimize recipe ingredient schema

Revision ID: 938eac76e95c
Revises: d9d86012563b
Create Date: 2026-03-11 20:05:20.054637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '938eac76e95c'
down_revision: Union[str, Sequence[str], None] = 'd9d86012563b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_recipeingredient_ingredient', 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index('idx_recipeingredient_recipe', 'recipe_ingredients', ['recipe_id'], unique=False)
    op.drop_constraint(op.f('recipe_ingredients_ingredient_id_fkey'), 'recipe_ingredients', type_='foreignkey')
    op.drop_constraint(op.f('recipe_ingredients_recipe_id_fkey'), 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe_ingredients', 'ingredients', ['ingredient_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_recipe_diet', 'recipes', ['diet_type'], unique=False)
    op.add_column('recommendation_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('recommendation_logs', sa.Column('ingredients', sa.Text(), nullable=True))
    op.alter_column('recommendation_logs', 'recommended_recipe_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('recommendation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_recommendation_logs_id'), table_name='recommendation_logs')
    op.create_foreign_key(None, 'recommendation_logs', 'auth_users', ['user_id'], ['id'])
    op.drop_column('recommendation_logs', 'request_payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_logs', sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recommendation_logs', type_='foreignkey')
    op.create_index(op.f('ix_recommendation_logs_id'), 'recommendation_logs', ['id'], unique=False)
    op.alter_column('recommendation_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendation_logs', 'recommended_recipe_ids',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('recommendation_logs', 'ingredients')
    op.drop_column('recommendation_logs', 'user_id')
    op.drop_index('idx_recipe_diet', table_name='recipes')
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_ingredients_recipe_id_fkey'), 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'])
    op.create_foreign_key(op.f('recipe_ingredients_ingredient_id_fkey'), 'recipe_ingredients', 'ingredients', ['ingredient_id'], ['id'])
    op.drop_index('idx_recipeingredient_recipe', table_name='recipe_ingredients')
    op.drop_index('idx_recipeingredient_ingredient', table_name='recipe_ingredients')
    # ### end Alembic commands ###
